services:
  tux:
    build: .
    image: allthingslinux/tux:latest
    container_name: tux
    restart: always
    develop:
      watch:
        - action: sync
          path: .
          target: /app/
          ignore:
            - .venv/
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: {}
