name: tux

services:
  bot:
    build: .
    container_name: tux-bot
    restart: always
    # environment:
    #   - TUX_ENV=dev
    develop:
      watch:
        - action: sync
          path: .
          target: /app/
          ignore:
            - .venv/
    env_file:
      - path: ./.env.dev
        required: true
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: tux-db
    restart: always
    shm_size: 128mb
    env_file:
      - path: ./.env.dev
        required: true
    volumes:
      - tux_data:/var/lib/postgresql/data
      - ./scripts/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
    entrypoint: ["/docker-entrypoint-initdb.d/postgres-init.sh"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

  # adminer:
  #   image: adminer
  #   container_name: tux-adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  tux_data:
