name: tux

services:

  bot:
    build: .
    container_name: tux_bot
    restart: always
    develop:
      watch:
        - action: sync
          path: .
          target: /app/
          ignore:
            - .venv/
            - .cache/
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: poetry.lock
    env_file:
      - path: .env
        required: true
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "poetry install --no-root && poetry run prisma db push && poetry run prisma generate && poetry run python tux/main.py"]

  db:
    image: postgres
    container_name: tux_db
    restart: always
    shm_size: 128mb
    env_file:
      - path: .env
        required: true
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    container_name: tux_adminer
    restart: always
    ports:
      - 8080:8080
    env_file:
      - path: .env
        required: true
    environment:
      ADMINER_DEFAULT_DRIVER: "pgsql"
      ADMINER_DEFAULT_SERVER: "db"
      ADMINER_DEFAULT_DB: ${POSTGRES_DB}
      ADMINER_DEFAULT_USERNAME: ${POSTGRES_USER}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["sh", "-c", "php -S 0.0.0.0:8080 -t /var/www/html"]
    configs:
      - source: adminer-index.php
        target: /var/www/html/index.php
    depends_on:
      db:
        condition: service_healthy
      bot:
        condition: service_started

configs:
  adminer-index.php:
    content: |
      <?php
        if(!count($$_GET)) {
          $$_POST['auth'] = [
            'server' => $$_ENV['ADMINER_DEFAULT_SERVER'],
            'username' => $$_ENV['ADMINER_DEFAULT_USERNAME'],
            'password' => $$_ENV['ADMINER_DEFAULT_PASSWORD'],
            'driver' => $$_ENV['ADMINER_DEFAULT_DRIVER'],
            'db'    => $$_ENV['ADMINER_DEFAULT_DB'],
          ];
        }
        include './adminer.php';
      ?>

volumes:
  data: