services:
  tux:
    build: .
    image: allthingslinux/tux:latest
    container_name: tux
    restart: always
    volumes:
      - type: bind
        source: .
        target: /app/
    env_file:
      - .env