name: Pyright

on: [push, pull_request]

jobs:
  pyright:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install root project
        run: poetry install --no-interaction

      - name: Add Poetry to PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Generate Prisma Client
        run: poetry run prisma generate

      - name: Debug environment
        run: |
          echo "Python location: $(which python)"
          echo "Poetry location: $(which poetry)"
          poetry --version
          which pyright

      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
        with:
          version: "PATH"
          working-directory: "."
          python-platform: "Linux"
          python-version: "3.12"
          annotate: "all"